### ISSUE TITLE
Refactoring plan 

### ISSUE THREAD

**Issue by nobuyuki83** [maronuu/ICP#1]
- [x] Please remove the `build` folder (add `build` folder in the `.gitignore`)
- [x] Please move `src/icp.cpp` to `include/icp.cpp` (you might feel strange to see *.cpp in the `include` directory, but it's OK)
- [x] change name `src` to `00_demo2d`(assign name begin with number for each demo)
- [x] write some cmake command to use Eigen library (https://yuki-koyama.hatenablog.com/entry/2019/03/15/091206)
- [x] specify minimum cmake version (Use 3.12), C++ language version (Use C++17), project name "00_demo2d" https://github.com/maronuu/ICP/blob/76dbb20431c51bf47c024c5802d34f30a578f034/src/CMakeLists.txt#L1
- [x] Use googletest for test https://github.com/maronuu/ICP/blob/76dbb20431c51bf47c024c5802d34f30a578f034/test/CMakeLists.txt#L1

**Comment by maronuu** [comment]
Static library `my_icp` from `icp.cpp/hpp` is built, so changed name `include` to `my_icp`.

**Comment by maronuu** [comment]
forgot to make branch for this issue...
will do next time.

**Comment by nobuyuki83** [comment]
Thanks for taking care of this. All the changes look good. Closing this issue.
